servers:
  - url: https://api.letta.com
    description: Letta Cloud
    x-fern-server-name: Letta Cloud
  - url: http://localhost:8283
    description: Self-hosted
    x-fern-server-name: Self-hosted

paths:
  /v1/tools/{tool_id}:
    get:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: retrieve
    delete:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: modify
  /v1/tools/:
    get:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: create
    put:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: upsert
  /v1/tools/add-base-tools:
    post:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: add_base_tool
  /v1/sources/{source_id}:
    get:
      x-fern-sdk-group-name:
        - sources
      x-fern-sdk-method-name: retrieve
    delete:
      x-fern-sdk-group-name:
        - sources
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - sources
      x-fern-sdk-method-name: modify
  /v1/sources/name/{source_name}:
    get:
      x-fern-sdk-group-name:
        - sources
      x-fern-sdk-method-name: getByName
  /v1/sources/:
    get:
      x-fern-sdk-group-name:
        - sources
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - sources
      x-fern-sdk-method-name: create
  /v1/sources/{source_id}/upload:
    post:
      x-fern-sdk-group-name:
        - sources
        - files
      x-fern-sdk-method-name: upload
  /v1/sources/{source_id}/passages:
    get:
      x-fern-sdk-group-name:
        - sources
        - passages
      x-fern-sdk-method-name: list
  /v1/sources/{source_id}/files:
    get:
      x-fern-sdk-group-name:
        - sources
        - files
      x-fern-sdk-method-name: list
  /v1/sources/{source_id}/{file_id}:
    delete:
      x-fern-sdk-group-name:
        - sources
        - files
      x-fern-sdk-method-name: delete
  /v1/agents/:
    get:
      x-fern-sdk-group-name:
        - agents
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - agents
      x-fern-sdk-method-name: create
  /v1/agents/{agent_id}:
    get:
      x-fern-sdk-group-name:
        - agents
      x-fern-sdk-method-name: retrieve
    delete:
      x-fern-sdk-group-name:
        - agents
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - agents
      x-fern-sdk-method-name: modify
  /v1/agents/search:
    post:
      x-fern-sdk-group-name:
        - agents
      x-fern-sdk-method-name: search
      description: |
        <Note>This endpoint is only available on Letta Cloud.</Note>

        Search deployed agents.
  /v1/agents/{agent_id}/context:
    get:
      x-fern-sdk-group-name:
        - agents
        - context
      x-fern-sdk-method-name: retrieve
  /v1/agents/{agent_id}/tools:
    get:
      x-fern-sdk-group-name:
        - agents
        - tools
      x-fern-sdk-method-name: list
  /v1/agents/{agent_id}/tools/attach/{tool_id}:
    patch:
      x-fern-sdk-group-name:
        - agents
        - tools
      x-fern-sdk-method-name: attach
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: tool_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/tools/detach/{tool_id}:
    patch:
      x-fern-sdk-group-name:
        - agents
        - tools
      x-fern-sdk-method-name: detach
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: tool_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/sources:
    get:
      x-fern-sdk-group-name:
        - agents
        - sources
      x-fern-sdk-method-name: list
  /v1/agents/{agent_id}/core-memory:
    get:
      x-fern-sdk-group-name:
        - agents
        - core_memory
      x-fern-sdk-method-name: retrieve
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/core-memory/blocks:
    get:
      x-fern-sdk-group-name:
        - agents
        - blocks
      x-fern-sdk-method-name: list
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/core-memory/blocks/attach/{block_id}:
    patch:
      x-fern-sdk-group-name:
        - agents
        - blocks
      x-fern-sdk-method-name: attach
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: block_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/core-memory/blocks/detach/{block_id}:
    patch:
      x-fern-sdk-group-name:
        - agents
        - blocks
      x-fern-sdk-method-name: detach
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: block_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/core-memory/blocks/{block_label}:
    get:
      x-fern-sdk-group-name:
        - agents
        - blocks
      x-fern-sdk-method-name: retrieve
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: block_label
          in: path
          required: true
          schema:
            type: string
    patch:
      x-fern-sdk-group-name:
        - agents
        - blocks
      x-fern-sdk-method-name: modify
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: block_label
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/archival-memory:
    get:
      x-fern-sdk-group-name:
        - agents
        - passages
      x-fern-sdk-method-name: list
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
    post:
      x-fern-sdk-group-name:
        - agents
        - passages
      x-fern-sdk-method-name: create
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/archival-memory/{memory_id}:
    delete:
      x-fern-sdk-group-name:
        - agents
        - passages
      x-fern-sdk-method-name: delete
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: memory_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/messages:
    get:
      x-fern-sdk-group-name:
        - agents
        - messages
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - agents
        - messages
      x-fern-sdk-method-name: create
  /v1/agents/{agent_id}/messages/{message_id}:
    patch:
      x-fern-sdk-group-name:
        - agents
        - messages
      x-fern-sdk-method-name: modify
  /v1/agents/{agent_id}/messages/async:
    post:
      x-fern-sdk-group-name:
        - agents
        - messages
      x-fern-sdk-method-name: create_async
  /v1/agents/{agent_id}/messages/stream:
    post:
      x-fern-streaming:
        format: sse
      x-fern-sdk-group-name:
        - agents
        - messages
      x-fern-sdk-method-name: create_stream
      responses:
        '200':
          content:
            text/event-stream:
              schema:
                x-fern-type-name: LettaStreamingResponse
                oneOf:
                  - $ref: '#/components/schemas/SystemMessage'
                  - $ref: '#/components/schemas/UserMessage'
                  - $ref: '#/components/schemas/ReasoningMessage'
                  - $ref: '#/components/schemas/ToolCallMessage'
                  - $ref: '#/components/schemas/ToolReturnMessage'
                  - $ref: '#/components/schemas/AssistantMessage'
                  - $ref: '#/components/schemas/LettaUsageStatistics'
  /v1/agents/{agent_id}/template:
    post:
      x-fern-sdk-group-name:
        - agents
        - templates
      x-fern-sdk-method-name: create
      description: |
        <Note>This endpoint is only available on Letta Cloud.</Note>

        Creates a template from an agent.
  /v1/agents/{agent_id}/migrate:
    post:
      x-fern-sdk-group-name:
        - agents
        - templates
      x-fern-sdk-method-name: migrate
      description: |
        <Note>This endpoint is only available on Letta Cloud.</Note>

        Migrate an agent to a new versioned agent template.
  /v1/agents/{agent_id}/version-template:
    post:
      x-fern-sdk-group-name:
        - agents
        - templates
      x-fern-sdk-method-name: create_version
      description: |
        <Note>This endpoint is only available on Letta Cloud.</Note>

        Creates a new version of the template version of the agent.
  /v1/agents/{agent_id}/core-memory/variables:
    get:
      x-fern-sdk-group-name:
        - agents
        - memory_variables
      x-fern-sdk-method-name: list
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
      description: |
        <Note>This endpoint is only available on Letta Cloud.</Note>

        Returns the memory variables associated with an agent.
  /v1/agents/{agent_id}/sources/attach/{source_id}:
    patch:
      x-fern-sdk-group-name:
        - agents
        - sources
      x-fern-sdk-method-name: attach
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: source_id
          in: path
          required: true
          schema:
            type: string
  /v1/agents/{agent_id}/sources/detach/{source_id}:
    patch:
      x-fern-sdk-group-name:
        - agents
        - sources
      x-fern-sdk-method-name: detach
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: source_id
          in: path
          required: true
          schema:
            type: string
  /v1/models/:
    get:
      x-fern-sdk-group-name:
        - models
      x-fern-sdk-method-name: list_llms
  /v1/models/embedding:
    get:
      x-fern-sdk-group-name:
        - models
      x-fern-sdk-method-name: list_embedding_models
  /v1/blocks/:
    get:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: create
  /v1/blocks/{block_id}:
    get:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: retrieve
    delete:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: delete
    patch:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: modify
  /v1/jobs/:
    get:
      x-fern-sdk-group-name:
        - jobs
      x-fern-sdk-method-name: list
  /v1/jobs/active:
    get:
      x-fern-sdk-group-name:
        - jobs
      x-fern-sdk-method-name: listActive
  /v1/jobs/{job_id}:
    get:
      x-fern-sdk-group-name:
        - jobs
      x-fern-sdk-method-name: retrieve
    delete:
      x-fern-sdk-group-name:
        - jobs
      x-fern-sdk-method-name: delete
  /v1/health/:
    get:
      x-fern-sdk-group-name:
        - health
      x-fern-sdk-method-name: check
  /v1/templates/{project}/{template_version}/agents:
    post:
      x-fern-sdk-group-name:
        - templates
      x-fern-sdk-method-name: create_agents
  /v1/identities/:
    get:
      x-fern-sdk-group-name:
        - identities
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - identities
      x-fern-sdk-method-name: create
    put:
      x-fern-sdk-group-name:
        - identities
      x-fern-sdk-method-name: upsert
  /v1/identities/{identity_id}:
    get:
      x-fern-sdk-group-name:
        - identities
      x-fern-sdk-method-name: retrieve
    patch:
      x-fern-sdk-group-name:
        - identities
      x-fern-sdk-method-name: modify
    delete:
      x-fern-sdk-group-name:
        - identities
      x-fern-sdk-method-name: delete
  /v1/groups/:
    get:
      x-fern-sdk-group-name:
        - groups
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - groups
      x-fern-sdk-method-name: create
  /v1/groups/{group_id}:
    get:
      x-fern-sdk-group-name:
        - groups
      x-fern-sdk-method-name: retrieve
    patch:
      x-fern-sdk-group-name:
        - groups
      x-fern-sdk-method-name: modify
    delete:
      x-fern-sdk-group-name:
        - groups
      x-fern-sdk-method-name: delete
  /v1/groups/{group_id}/reset-messages:
    patch:
      x-fern-sdk-group-name:
        - groups
      x-fern-sdk-method-name: reset_messages
  /v1/groups/{group_id}/messages:
    get:
      x-fern-sdk-group-name:
        - groups
        - messages
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - groups
        - messages
      x-fern-sdk-method-name: create
  /v1/groups/{group_id}/messages/{message_id}:
    patch:
      x-fern-sdk-group-name:
        - groups
        - messages
      x-fern-sdk-method-name: modify
  /v1/groups/{group_id}/messages/stream:
    post:
      x-fern-streaming:
        format: sse
      x-fern-sdk-group-name:
        - groups
        - messages
      x-fern-sdk-method-name: create_stream
      responses:
        '200':
          content:
            text/event-stream:
              schema:
                x-fern-type-name: LettaStreamingResponse
                oneOf:
                  - $ref: '#/components/schemas/SystemMessage'
                  - $ref: '#/components/schemas/UserMessage'
                  - $ref: '#/components/schemas/ReasoningMessage'
                  - $ref: '#/components/schemas/ToolCallMessage'
                  - $ref: '#/components/schemas/ToolReturnMessage'
                  - $ref: '#/components/schemas/AssistantMessage'
                  - $ref: '#/components/schemas/LettaUsageStatistics'
  /v1/messages/batches:
    post:
      x-fern-sdk-group-name:
        - messages
        - batches
      x-fern-sdk-method-name: create
    get:
      x-fern-sdk-group-name:
        - messages
        - batches
      x-fern-sdk-method-name: list
  /v1/messages/batches/{batch_id}:
    get:
      x-fern-sdk-group-name:
        - messages
        - batches
      x-fern-sdk-method-name: retrieve
    patch:
      x-fern-sdk-group-name:
        - messages
        - batches
      x-fern-sdk-method-name: cancel
  /v1/projects:
    get:
      x-fern-sdk-group-name:
        - projects
      x-fern-sdk-method-name: list
  /v1/client-side-access-tokens:
    post:
      x-fern-sdk-group-name:
        - client-side-access-tokens
      x-fern-sdk-method-name: create
  /v1/client-side-access-tokens/{token}:
    delete:
        x-fern-sdk-group-name:
            - client-side-access-tokens
        x-fern-sdk-method-name: delete
  /v1/templates:
    get:
      x-fern-sdk-group-name:
        - templates
      x-fern-sdk-method-name: list
