steps:

  # Install gcloud, kubectl, npx, just, gke-gcloud-auth-plugin, helm, then run build and deploy
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -exo pipefail

        # Install gcloud
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        apt-get update && apt-get install -y google-cloud-sdk

        # Install kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
        kubectl version --client

        # Install Node.js and npm (which includes npx)
        curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
        apt-get install -y nodejs
        npx --version

        # Install just
        curl -LSs https://just.systems/install.sh | bash -s -- --to ./

        # Install gke-gcloud-auth-plugin
        apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        apt-get update && apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

        # Install Helm
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

        # Run build and deploy
        ./just configure-docker
        ./just configure-kubectl
        ./just check-github-status
        ./just build
        ./just deploy

substitutions:
  _REGION: us-central1
  _REGISTRY_NAME: letta

options:
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'DOCKER_REGISTRY=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}'
    - 'TAG=$COMMIT_SHA'
    - 'DATABASE_URL=${_DATABASE_URL}'
    - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
    - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
    - 'GOOGLE_REDIRECT_URI=${_GOOGLE_REDIRECT_URI}'
    - 'LETTA_AGENTS_ENDPOINT=${_LETTA_AGENTS_ENDPOINT}'
    - 'MIXPANEL_TOKEN=${_MIXPANEL_TOKEN}'
    - 'NEXT_PUBLIC_MIXPANEL_TOKEN=${_MIXPANEL_TOKEN}'
    - 'LAUNCH_DARKLY_SDK_KEY=${_LAUNCH_DARKLY_SDK_KEY}'
    - 'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}'
    - 'NEXT_PUBLIC_CURRENT_HOST=${_NEXT_PUBLIC_CURRENT_HOST}'
    - 'REDIS_HOST=${_REDIS_HOST}'
    - 'SLACK_WEBHOOK_URL=${_SLACK_WEBHOOK_URL}'
    - 'GITHUB_READ_STATUS_TOKEN=${_GITHUB_READ_STATUS_TOKEN}'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'
