version: '3.7'
services:
    redis:
      image: redis:alpine
      container_name: redis
      healthcheck:
        test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
        interval: 1s
        timeout: 3s
        retries: 5
      ports:
        - "6379:6379"
      volumes:
        - ./data:/data
      command: redis-server --appendonly yes
    web:
      depends_on:
        redis:
          condition: service_healthy
      container_name: letta-web
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "3000:3000"

