version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: redis
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes
  postgres:
    image: ankane/pgvector
    container_name: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: letta
    volumes:
      - ./misc/postgres-db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: letta-web
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/letta
      REDIS_URL: redis://redis:6379
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      LETTA_AGENTS_ENDPOINT: ${LETTA_AGENTS_ENDPOINT}
      NEXT_PUBLIC_CURRENT_HOST: ${NEXT_PUBLIC_CURRENT_HOST}

  migrations:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: letta-migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/letta
