export const LOCAL_PROJECT_SERVER_HOST = 'localhost';
export const LOCAL_PROJECT_SERVER_PORT = 8283;
export const LOCAL_PROJECT_SERVER_URL = `http://${LOCAL_PROJECT_SERVER_HOST}:${LOCAL_PROJECT_SERVER_PORT}`;
