import { generateOpenApi } from '@ts-rest/open-api';
import { sdkContracts } from '$letta/sdk/contracts';
import fs from 'fs';
import path from 'path';
import { DEPLOYMENT_BASE_URL } from '$letta/sdk/shared';
import { isErrorResult, merge } from 'openapi-merge';

const openApiDoc = generateOpenApi(
  sdkContracts,
  {
    info: {
      title: 'Letta API',
      version: '1.0.0',
    },
  },
  {
    setOperationId: 'concatenated-path',
  }
);

const result = merge([
  {
    oas: openApiDoc as any,
    pathModification: {
      prepend: DEPLOYMENT_BASE_URL,
    },
  },
]);

if (isErrorResult(result)) {
  console.error(`${result.message} (${result.type})`);
  process.exit(1);
}

fs.writeFileSync(
  path.join(__dirname, '..', 'autogenerated', 'letta-web-openapi.json'),
  JSON.stringify(result.output, null, 2)
);
