import baseConfig from '../../eslint.config.mjs';

export default [
  {
    ignores: ['**/dist', '**/_autogenerated/**'],
  },
  ...baseConfig,
  {
    files: ['**/*.ts', '**/*.tsx'],
    // Override or add rules here
    rules: {},
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    // Override or add rules here
    rules: {},
  },
];
