[project]
name = "desktop-core"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "letta[desktop,postgres,sqlite,cloud-tool-sandbox]",
    "pyinstaller>=6.15.0",
    "pgserver",
]

[tool.uv.sources]
letta = { path = "../core" }
