apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env-secret
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  GRAFANA_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ index .Values.grafana.datasources "datasources.yaml" "datasources" 0 "secureJsonData" "password" | b64enc | quote }}
