import type { AgentState } from './lib/_autogenerated/requests';

export * from './lib/LettaAgentsAPIWrapper/LettaAgentsAPIWrapper';
export * from './lib/types';
export * from './lib/_autogenerated/queries';
export * from './lib/_autogenerated/requests';
export * from './lib/constants';
export * from './lib/hooks/useResetAllLettaAgentsQueryKeys/useResetAllLettaAgentsQueryKeys';

export function getIsAgentState(data: unknown): data is AgentState {
  return Object.prototype.hasOwnProperty.call(data, 'tools');
}
