import type { ApiError } from '../../_autogenerated/requests/core/ApiError';

export function isAPIError(
  error: unknown,
): error is ApiError & { body: { detail?: string } } {
  return Object.prototype.hasOwnProperty.call(error, 'body');
}
