import type { ApiError } from '../../_autogenerated/requests/core/ApiError';

export function isAPIError(
  error: unknown,
): error is ApiError & {
  body: {
    detail?: string;
    errorCode?: string;
    [key: string]: string | undefined;
  };
} {
  return Object.prototype.hasOwnProperty.call(error, 'body');
}
