import type { ApiError } from '../../_autogenerated/requests/core/ApiError';

export function isAPIError(error: unknown): error is ApiError {
  return Object.prototype.hasOwnProperty.call(error, 'body');
}
