import {
  getToolErrorRatePerDay,
  getToolErrorRateByName,
  getLLMLatencyPerDay,
  getToolLatencyPerDay,
  getToolLatencyByName,
  getToolUsageByFrequency,
  getTimeToFirstTokenPerDay,
  getStepDurationMetrics,
  getTotalMessagesPerDay,
  getToolErrorsMetrics,
  getToolErrorMessages,
  getTimeToFirstTokenMetrics,
  getAverageResponseTime,
  getActiveAgentsPerDay,
  getTimeToFirstTokenMessages,
  getObservabilityOverview,
  getApiErrorCount,
  getLLMLatencyByModel,
  getTracesByProjectId,
} from './handlers';

export const observabilityRouter = {
  // New metrics endpoints
  getToolErrorRatePerDay,
  getToolErrorRateByName,
  getLLMLatencyPerDay,
  getToolLatencyPerDay,
  getToolLatencyByName,
  getToolUsageByFrequency,
  getTimeToFirstTokenPerDay,
  getStepDurationMetrics,
  getTotalMessagesPerDay,
  getLLMLatencyByModel,
  // Existing endpoints
  getTracesByProjectId,
  getTimeToFirstTokenMetrics,
  getTimeToFirstTokenMessages,
  getAverageResponseTime,
  getActiveAgentsPerDay,
  getToolErrorsMetrics,
  getToolErrorMessages,
  getObservabilityOverview,
  getApiErrorCount,
};
