grafana:
  service:
    port: 3002
  containerPort: 3000
  persistence:
    enabled: true
    size: 10Gi
  adminUser: admin
  adminPassword: ""
  plugins:
    - grafana-clickhouse-datasource
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: ClickHouse
          type: grafana-clickhouse-datasource
          uid: clickhouse
          url: ""
          access: proxy
          isDefault: true
          jsonData:
            defaultDatabase: ""
            protocol: https
            username: ""
            tlsSkipVerify: true
          secureJsonData:
            password: ""
