grafana:
  service:
    port: 3002
  containerPort: 3000
  persistence:
    enabled: true
    size: 10Gi
  adminUser: admin
  adminPassword: ""
  plugins:
    - grafana-clickhouse-datasource
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: ClickHouse
          type: grafana-clickhouse-datasource
          uid: clickhouse
          url: http://10.0.0.84:8123
          access: proxy
          isDefault: true
          jsonData:
            defaultDatabase: otel
            server: 10.0.0.84
            port: 8123
            protocol: http
            username: default
            tlsSkipVerify: true
          secureJsonData:
            password: ""
