export * from './anthropic';
export * from './claude';
export * from './composio';
export * from './discord';
export * from './google';
export * from './letta';
export * from './llama';
export * from './meta';
export * from './mistral';
export * from './nous-research';
export * from './nvidia';
export * from './openai';
export * from './qwen';
export * from './snorkel-ai';
export * from './together-ai';
export type BrandKeys =
  | 'affinity'
  | 'agencyzoom'
  | 'airtable'
  | 'anthropic'
  | 'asana'
  | 'attio'
  | 'bamboohr'
  | 'bitbucket'
  | 'blackboard'
  | 'brevo'
  | 'browserbase'
  | 'calendly'
  | 'canva'
  | 'canvas'
  | 'claude'
  | 'clickup'
  | 'codeinterpreter'
  | 'composio'
  | 'discord'
  | 'docusign'
  | 'dropbox'
  | 'dynamics365'
  | 'elevenlabs'
  | 'entelligence'
  | 'exa'
  | 'figma'
  | 'firecrawl'
  | 'freshdesk'
  | 'github'
  | 'gmail'
  | 'google_drive'
  | 'google'
  | 'googlebigquery'
  | 'googlecalendar'
  | 'googledocs'
  | 'googledrive'
  | 'googlemeet'
  | 'googlesheets'
  | 'googletasks'
  | 'hackernews'
  | 'heygen'
  | 'hubspot'
  | 'induced_ai'
  | 'jira'
  | 'junglescout'
  | 'klaviyo'
  | 'letta'
  | 'linear'
  | 'linkedin'
  | 'listennotes'
  | 'llama'
  | 'lmnt'
  | 'mailchimp'
  | 'mem0'
  | 'meta'
  | 'microsoft_clarity'
  | 'microsoft_teams'
  | 'mistral'
  | 'multionai'
  | 'notion'
  | 'nous-research'
  | 'nvidia'
  | 'one_drive'
  | 'openai'
  | 'outlook'
  | 'peopledatalabs'
  | 'perplexityai'
  | 'pipedrive'
  | 'posthog'
  | 'qwen'
  | 'reddit'
  | 'retellai'
  | 'rocketlane'
  | 'salesforce'
  | 'sendgrid'
  | 'serpapi'
  | 'share_point'
  | 'shopify'
  | 'slack'
  | 'snorkel-ai'
  | 'snowflake'
  | 'supabase'
  | 'tavily'
  | 'together-ai'
  | 'trello'
  | 'twitter'
  | 'weathermap'
  | 'wrike'
  | 'yousearch'
  | 'youtube'
  | 'zendesk'
  | 'zoom';
