import React from 'react';
import {
  AzureLogoMarkDynamic,
  GeminiLogoMarkDynamic,
  GithubLogoMarkDynamic,
  LmstudioLogoMarkDynamic,
  OllamaLogoMarkDynamic,
} from '../../../_autogenerated';
import type { BrandKeys } from '../../../_autogenerated';
import { ComposioLogoMarkDynamic } from '../../../_autogenerated';
import {
  NvidiaLogoMarkDynamic,
  TogetherAiLogoMarkDynamic,
} from '../../../_autogenerated';
import {
  GoogleLogoMarkDynamic,
  SnorkelAiLogoMarkDynamic,
} from '../../../_autogenerated';
import { NousResearchLogoMarkDynamic } from '../../../_autogenerated';
import {
  AnthropicLogoMarkDynamic,
  ClaudeLogoMarkDynamic,
  DiscordLogoMarkDynamic,
  LlamaLogoMarkDynamic,
  QwenLogoMarkDynamic,
} from '../../../_autogenerated';
import { MistralLogoMarkDynamic } from '../../../_autogenerated';
import {
  LettaLogoMarkDynamic,
  MetaLogoMarkDynamic,
} from '../../../_autogenerated';
import { OpenaiLogoMarkDynamic } from '../../../_autogenerated';

export const brandKeyToNameMap: Record<BrandKeys, string> = {
  openai: 'OpenAI',
  letta: 'Letta',
  meta: 'Meta',
  mistral: 'Mistral',
  anthropic: 'Anthropic',
  discord: 'Discord',
  claude: 'Claude',
  llama: 'Llama',
  qwen: 'Qwen',
  'nous-research': 'Nous Research',
  google: 'Google',
  nvidia: 'Nvidia',
  'snorkel-ai': 'Snorkel AI',
  'together-ai': 'Together AI',
  composio: 'Composio',
  github: 'GitHub',
  gemini: 'Gemini',
  azure: 'Azure',
  lmstudio: 'LM Studio',
  ollama: 'Ollama',
};

export const brandKeyToOwnerMap: Record<BrandKeys, string> = {
  openai: 'OpenAI',
  letta: 'Letta',
  meta: 'Meta',
  mistral: 'Mistral',
  anthropic: 'Anthropic',
  discord: 'Discord',
  claude: 'Anthropic',
  llama: 'Meta',
  qwen: 'Qwen',
  'nous-research': 'Nous Research',
  google: 'Google',
  nvidia: 'Nvidia',
  'snorkel-ai': 'Snorkel AI',
  'together-ai': 'Together AI',
  composio: 'Composio',
  github: 'GitHub',
  gemini: 'Google',
  azure: 'Microsoft',
  lmstudio: 'LM Studio',
  ollama: 'Ollama',
};

export function isBrandKey(brandKey: string): brandKey is BrandKeys {
  return brandKey in brandKeyToNameMap;
}

export function brandKeyToName(brandKey: BrandKeys) {
  return brandKeyToNameMap[brandKey];
}

export const brandKeyToLogoMap: Record<BrandKeys, React.ReactNode> = {
  openai: <OpenaiLogoMarkDynamic />,
  letta: <LettaLogoMarkDynamic />,
  meta: <MetaLogoMarkDynamic />,
  mistral: <MistralLogoMarkDynamic />,
  anthropic: <AnthropicLogoMarkDynamic />,
  discord: <DiscordLogoMarkDynamic />,
  claude: <ClaudeLogoMarkDynamic />,
  llama: <LlamaLogoMarkDynamic />,
  qwen: <QwenLogoMarkDynamic />,
  'nous-research': <NousResearchLogoMarkDynamic />,
  google: <GoogleLogoMarkDynamic />,
  nvidia: <NvidiaLogoMarkDynamic />,
  'snorkel-ai': <SnorkelAiLogoMarkDynamic />,
  'together-ai': <TogetherAiLogoMarkDynamic />,
  composio: <ComposioLogoMarkDynamic />,
  gemini: <GeminiLogoMarkDynamic />,
  github: <GithubLogoMarkDynamic />,
  ollama: <OllamaLogoMarkDynamic />,
  azure: <AzureLogoMarkDynamic />,

  lmstudio: <LmstudioLogoMarkDynamic />,
};

export function brandKeyToLogo(brandKey: BrandKeys) {
  return brandKeyToLogoMap[brandKey];
}
