"""add project constraint on tools

Revision ID: 39577145c45d
Revises: d0880aae6cee
Create Date: 2025-12-17 15:46:06.184858

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import context, op


def is_sqlite() -> bool:
    """Check if we're running on SQLite."""
    return context.get_context().dialect.name == "sqlite"


# revision identifiers, used by Alembic.
revision: str = "39577145c45d"
down_revision: Union[str, None] = "d0880aae6cee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table("tools", schema=None) as batch_op:
            batch_op.create_unique_constraint("uix_organization_project_name", ["organization_id", "project_id", "name"])
    else:
        op.create_unique_constraint(
            "uix_organization_project_name", "tools", ["organization_id", "project_id", "name"], postgresql_nulls_not_distinct=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table("tools", schema=None) as batch_op:
            batch_op.drop_constraint("uix_organization_project_name", type_="unique")
    else:
        op.drop_constraint("uix_organization_project_name", "tools", type_="unique")
    # ### end Alembic commands ###
