apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-proxy.fullname" . }}-env
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  LETTA_AGENTS_ENDPOINT: {{ .Values.env.LETTA_AGENTS_ENDPOINT | b64enc | quote }}
