export enum ApplicationServices {
  CREATE_API_KEY = 'CREATE_API_KEY',
  READ_API_KEYS = 'READ_API_KEYS',
  DELETE_API_KEY = 'DELETE_API_KEY',
  UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION',
  UPDATE_USERS_IN_ORGANIZATION = 'UPDATE_USERS_IN_ORGANIZATION',
  UPDATE_ORGANIZATION_ENVIRONMENT_VARIABLES = 'UPDATE_ORGANIZATION_ENVIRONMENT_VARIABLES',
  CREATE_AGENT = 'CREATE_AGENT',
  DELETE_AGENT = 'DELETE_AGENT',
  READ_AGENT = 'READ_AGENT',
  MESSAGE_AGENT = 'MESSAGE_AGENT',
  UPDATE_AGENT = 'UPDATE_AGENT',
  CREATE_TOOL = 'CREATE_TOOL',
  DELETE_TOOL = 'DELETE_TOOL',
  READ_TOOL = 'READ_TOOL',
  UPDATE_TOOL = 'UPDATE_TOOL',
  CREATE_DATA_SOURCE = 'CREATE_DATA_SOURCE',
  DELETE_DATA_SOURCE = 'DELETE_DATA_SOURCE',
  READ_DATA_SOURCE = 'READ_DATA_SOURCE',
  UPDATE_DATA_SOURCE = 'UPDATE_DATA_SOURCE',
  READ_BILLING = 'READ_BILLING',
  UPDATE_BILLING = 'UPDATE_BILLING',
  CONNECT_INTEGRATIONS = 'CONNECT_INTEGRATIONS',
}



