version: '3.8'

services:
  letta_server:
    image: ${LETTA_SERVER_IMAGE:-letta/letta:latest}
    container_name: letta-server
    hostname: letta
    restart: unless-stopped
    environment:
      LETTA_DEBUG: false
      LETTA_SERVER_HOST: 0.0.0.0
      LETTA_SERVER_PORT: 8283
    ports:
      - "8283:8283"
    volumes:
      - letta_data:/root/.letta
      - letta_logs:/var/log/letta
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8283/v1/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Letta Web Interface (automatically enabled if letta-web image is available)
  #letta_web:
  #  image: ${LETTA_WEB_IMAGE:-letta-web:local}
  #  container_name: letta-web
  #  restart: unless-stopped
  #  depends_on:
  #    letta_server:
  #      condition: service_healthy
  #  environment:
  #    LETTA_AGENTS_ENDPOINT: http://letta:8283
  #    HOST: 0.0.0.0
  #    PORT: 8080
  #    NODE_ENV: production
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - web_logs:/var/log/letta-web
  #  networks:
  #    - default
  #  healthcheck:
  #    test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
  #    interval: 30s
  #    timeout: 10s
  #    retries: 3
  #    start_period: 90s

networks:
  default:
    name: letta-network
    driver: bridge

volumes:
  postgres_data:
    driver: local
    name: letta-postgres-data
  letta_data:
    driver: local
    name: letta-data
  letta_logs:
    driver: local
    name: letta-logs
  web_logs:
    driver: local
    name: letta-web-logs
