apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "letta-web.fullname" . }}-migration
  labels:
    {{- include "letta-web.labels" . | nindent 4 }}
    job-name: {{ include "letta-web.fullname" . }}-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "letta-web.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}-migrations:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "run", "web:database:migrate:ci"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "letta-web.fullname" . }}-env
                  key: DATABASE_URL
