# secretProviderClass
{{- if .Values.secretsProvider.secrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "letta-web.k8sEnvServicePrefix" $ }}secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  provider: gke
  secretObjects:
{{- range .Values.secretsProvider.secrets }}
  - secretName: {{ include "letta-web.k8sEnvServicePrefix" $ }}{{ . | replace "_" "-" | lower }}
    data:
    - key: {{ include "letta-web.k8sEnvServicePrefix" $ }}{{ . | replace "_" "-" | lower }}
      objectName: {{ include "letta-web.k8sEnvServicePrefix" $ }}{{ . | replace "_" "-" | lower }}
    type: Opaque
{{- end }}
  parameters:
    secrets: |
{{- range .Values.secretsProvider.secrets }}
      {{/* this is the one place we must not use the k8s prefix */}}
      - resourceName: projects/{{ $.Values.project_id }}/secrets/{{ include "letta-web.envServicePrefix" $ }}{{ . }}/versions/latest
        path: {{ include "letta-web.k8sEnvServicePrefix" $ }}{{ . | replace "_" "-" | lower }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretprovidersyncing-{{ include "letta-web.k8sEnvServicePrefix" $ }}-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"

rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secretprovidersyncing-{{ include "letta-web.k8sEnvServicePrefix" $ }}-rolebinding
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secretprovidersyncing-{{ include "letta-web.k8sEnvServicePrefix" $ }}-role
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver-gke
  namespace: kube-system
{{- end }}
