apiVersion: v1
kind: Service
metadata:
  name: {{ include "memgpt-server.fullname" . }}-otel-collector
  labels:
    {{- include "memgpt-server.labels" . | nindent 4 }}
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  selector:
    {{- include "memgpt-server.selectorLabels" . | nindent 4 }}
    component: otel-collector
