apiVersion: v1
kind: ConfigMap
metadata:
  name: memgpt-server-otel-collector-config
  labels:
    {{- include "memgpt-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      clickhouse:
        endpoint: {{ .Values.otelCollector.clickhouse.endpoint | quote }}
        database: {{ .Values.otelCollector.clickhouse.database | quote }}
        username: {{ .Values.otelCollector.clickhouse.username | quote }}
        timeout: 10s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
