import type { Tool } from '../../_autogenerated/requests';

export function isLettaTool(toolType: Tool['tool_type']) {
  return [
    'letta_core',
    'letta_memory_core',
    'letta_multi_agent_core',
    'letta_sleeptime_core',
    'letta_voice_sleeptime_core',
    'letta_builtin',
    'letta_files_core',
  ].includes(toolType || '');
}
