import { Project } from 'ts-morph';
import * as path from 'path';

async function job() {
  const project = new Project();

  project.addSourceFilesAtPaths(
    path.join(
      __dirname,
      '..',
      'src',
      'lib',
      '_autogenerated',
      'requests',
      '*.ts'
    )
  );

  const sourceFile = project.getSourceFileOrThrow('services.gen.ts');

  sourceFile.getClasses().forEach((cls) => {
    cls.getMethods().forEach((method) => {
      console.log(method.getName());

      const hasHeaderParam = method.getParameters().some((param) => {
        return param.getName() === 'headers';
      });

      if (!hasHeaderParam) {
        method.addParameter({
          name: 'headers',
          type: 'Record<string, string>',
          hasQuestionToken: true,
        });
      }
    });
  });
}

job().catch(console.error);
