#!/bin/bash
# Check if there are any changes in the specified directories
CHANGED_FILES=$(git diff --cached --name-only)
MONITORED_PATHS=("apps/core" "apps/fern" "apps/cloud-api" "apps/web" "libs")
RUN_PRECOMMIT=false

for FILE in $CHANGED_FILES; do
  for MONITORED_PATH in "${MONITORED_PATHS[@]}"; do
    if [[ $FILE == $MONITORED_PATH* ]]; then
      RUN_PRECOMMIT=true
      break 2
    fi
  done
done

# Only run precommit if changes in monitored paths
if [ "$RUN_PRECOMMIT" = true ]; then
  echo "Changes detected in monitored paths, running precommit..."
  npm run precommit
else
  echo "No changes in monitored paths, skipping npm run precommit..."
  # Don't run npm precommit when there are no changes in monitored paths
fi

# Always run the core pre-commit
UV_PROJECT_ENVIRONMENT="apps/core/.venv" uvx pre-commit run --config=.pre-commit-config.yaml
