'use client';
import { OpenAPI } from '../_autogenerated/requests';
import type { PropsWithChildren } from 'react';

OpenAPI.BASE = '';
OpenAPI.HEADERS = {
  'Content-Type': 'application/json',
  'Cache-Control': 'no-cache',
};

export function LettaAgentsAPIWrapper({ children }: PropsWithChildren) {
  return children;
}
