{{- if .Values.authProxy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "temporal-worker-controller.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-metrics-reader
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "temporal-worker-controller.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "temporal-worker-controller.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "temporal-worker-controller.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "temporal-worker-controller.selectorLabels" . | nindent 4 }}
---
{{- end }}
