{{- if .Values.prometheus.enabled }}
{{ fail "prometheus isn't supported yet" }}
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    {{ include "temporal-worker-controller.labels" $ | indent 4 }}
  name: {{ .Release.Name }}-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "temporal-worker-controller.selectorLabels" $ | nindent 6 }}
---
{{- end }}
