{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s-service-account" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
    {{- include "temporal-worker-controller.labels" . | nindent 4 }}
---
{{- end }}
