name: ☁️ Cloud API Stability Test


permissions:
  actions: read
  contents: read

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: changed-files
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .github/workflows/migration-api-stability.yml
            apps/cloud-api/src/**
            apps/core/**
            libs/sdk-core/**
            libs/utils-server/**
            libs/service-database/**
            libs/config-environment-variables/**
            libs/service-redis/**
            libs/sdk-web/**
            package.json
            package-lock.json
            tsconfig.json
  cloud-api-test:
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5433/postgres
      LETTA_AGENTS_ENDPOINT: http://localhost:8283
      IS_API_STABILITY_TEST: yes
      IS_CYPRESS_RUN: yes
      NODE_OPTIONS: --max_old_space_size=6144
    needs: [changed-files]
    permissions:
      actions: read
      contents: read
      id-token: write
    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres-web:
        image: postgres
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres-core:
        image: pgvector/pgvector:pg17
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Set up python 3.12
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install just
        uses: extractions/setup-just@v3
        with:
          just-version: '1.42.2'

      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v4
        with:
          path: apps/core/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}${{ inputs.install-args || '-E dev -E postgres -E external-tools -E tests -E cloud-tool-sandbox' }}
          # Restore cache with this prefix if not exact match with key
          # Note cache-hit returns false in this case, so the below step will run
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}
      - name: Install uv dependencies
        if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
        shell: bash
        working-directory: apps/core
        run: uv sync --no-install-project ${{ inputs.install-args || '--extra postgres --extra external-tools --extra dev --extra cloud-tool-sandbox' }}
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Inject env vars into environment
        working-directory: apps/core
        run: |
          # Get secrets and mask them before adding to environment
          while IFS= read -r line || [[ -n "$line" ]]; do
            # Check if line is not empty
            if [[ -n "$line" ]]; then
              # Extract the value after the equals sign
              value=$(echo "$line" | cut -d= -f2-)
              # Mask the value so it doesn't appear in logs
              echo "::add-mask::$value"
              # Add to GitHub environment
              echo "$line" >> $GITHUB_ENV
            fi
          done < <(uvx --with google-cloud-secret-manager python3 ../../packer/base/files/letta_secrets_helper.py --env dev --service ci)
      - name: Migrate database
        working-directory: apps/core
        env:
          LETTA_PG_PORT: 5432
          LETTA_PG_USER: postgres
          LETTA_PG_PASSWORD: postgres
          LETTA_PG_DB: postgres
          LETTA_PG_HOST: localhost
        run: |
          psql -h localhost -U postgres -d postgres -c 'CREATE EXTENSION vector'
          uv run alembic upgrade head
      - name: Turn on Letta agents
        working-directory: apps/core
        env:
          LETTA_PG_PORT: 5432
          LETTA_PG_USER: postgres
          LETTA_PG_PASSWORD: postgres
          LETTA_PG_DB: postgres
          LETTA_PG_HOST: localhost
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        run: uv run letta server &
      - name: Cache npm dependencies
        id: cache-main
        uses: actions/cache@v3
        with:
          path: ./apps/cloud-api/node_modules
          key: modules-${{ hashFiles('./apps/cloud-api/package-lock.json') }}
      - name: Install deps
        working-directory: apps/cloud-api
        run: just setup-cloud-api
      - name: Migrate Cloud DB
        run:
          just migrate-cloud-db
      - name: Turn on cloud-api
        working-directory: apps/cloud-api
        run: just cloud-api &
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          NEXT_PUBLIC_CURRENT_HOST: http://localhost:3006
          IS_API_STABILITY_TEST: yes
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
      - name: Run tests
        run: just test-cloud-api
