name: Run Docker integration tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: docker-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-tests:
    uses: ./.github/workflows/reusable-test-workflow.yml
    with:
      test-type: 'docker'
      install-args: '-E dev -E postgres'
      timeout-minutes: 15
      use-docker: true
      changed-files-pattern: |
        apps/core/**
        libs/config-core-deploy/**
        .github/workflows/docker-integration-tests.yaml
    secrets: inherit
