name: Run Docker integration tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: docker-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-tests:
    uses: ./.github/workflows/reusable-test-workflow.yml
    with:
      test-type: 'docker'
      install-args: '--extra dev --extra postgres --extra sqlite'
      timeout-minutes: 15
      use-docker: true
      runner: '["self-hosted", "medium"]'
      ref: ${{ github.event.pull_request.head.sha || github.sha }}
      changed-files-pattern: |
        apps/core/**
        libs/config-core-deploy/**
        .github/workflows/reusable-test-workflow.yml
        .github/workflows/docker-integration-tests.yaml
    secrets: inherit
