name: 🌿 Fern Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check API is valid
        working-directory: apps
        run: fern check
