name: "Letta Web OpenAPI Compatibility Checker"


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  check-letta-web-compatibility:
    uses: letta-ai/letta-compatibility-workflows/.github/workflows/letta-web-openapi-compatibility-tester.yml@main
    secrets: inherit
