name: Sync With OSS

on:
  # 1) Triggered by a repository_dispatch from the OSS repo (letta)
  repository_dispatch:
    types: [oss-update]

  # 2) Triggered by a local push that touches files under apps/core/**
  push:
    branches: [main]
    paths:
      - 'apps/core/**'
      
  # 3) Manual trigger from GitHub web interface
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out private repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_PAT }}

      - name: Configure Git
        run: |
          git config user.name "Letta Sync Bot"
          git config user.email "bot@users.noreply.github.com"

      - name: Configure Git remote
        run: |
          git remote remove letta-oss || true
          git remote add letta-oss "https://x-access-token:${{ secrets.SYNC_PAT }}@github.com/letta-ai/letta.git"

      - name: Decide whether to pull or push
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Triggered by ${{ github.event_name }}. Pulling from OSS..."
            
            # Pull changes from the OSS repo into apps/core
            git subtree split --prefix=apps/core --rejoin
            git subtree pull --prefix=apps/core letta-oss main
            
            # If the pull added any new commits, commit and push them back to this private repo
            if ! git diff --quiet apps/core; then
              echo "New changes from OSS found. Committing..."
              git add apps/core
              git commit -m "Pull from OSS [sync-skip]"
              git push origin HEAD:main
              echo "Pushed updated subtree to private repo main."
            else
              echo "No new changes from OSS. Nothing to commit."
            fi

          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "Triggered by push to private repo. Pushing changes to OSS..."
            git subtree push --prefix apps/core letta-oss letta-automated-integration-branch
            echo "Subtree changes pushed to OSS."
          fi
