name: Test Undertaker

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: changed-files
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            apps/credit-undertaker/**
            libs/sdk-web/**
            libs/service-database/**
            libs/service-email/**
            libs/service-feature-flags/**
            libs/service-payments/**
            libs/service-rbac/**
            libs/service-redis/**
            libs/types/**
            libs/utils-server/**
            libs/utils-shared/**
            libs/service-analytics/**
            libs/config-agent-starter-kits/**
            libs/service-auth/**
            .github/workflows/test-undertaker.yml
  main:
    needs: [ changed-files ]
    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: apps/credit-undertaker/package.json
          node-version-file: '.nvmrc'
      - name: Install just
        uses: extractions/setup-just@v3
        with:
          just-version: '1.42.2'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: just build-undertaker
