name: Unit Tests

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  COMPOSIO_API_KEY: ${{ secrets.COMPOSIO_API_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-core-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        test_suite:
          - "test_local_client.py"
          - "test_client.py"
          - "test_server.py"
          - "test_managers.py"
          - "test_tools.py"
          - "test_o1_agent.py"
          - "test_tool_rule_solver.py"
          - "test_agent_tool_graph.py"
    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run container
        run: bash db/run_postgres.sh

      - name: Setup Python, Poetry, and Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: "3.12"
          poetry-version: "1.8.2"
          install-args: "-E dev -E postgres -E milvus -E external-tools -E tests"

      - name: Run core unit tests
        env:
          LETTA_PG_PORT: 8888
          LETTA_PG_USER: letta
          LETTA_PG_PASSWORD: letta
          LETTA_PG_DB: letta
          LETTA_PG_HOST: localhost
          LETTA_SERVER_PASS: test_server_token
        run: |
          poetry run pytest -s -vv tests/${{ matrix.test_suite }}

  misc-unit-tests:
    runs-on: ubuntu-latest
    needs: run-core-unit-tests
    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run container
        run: bash db/run_postgres.sh

      - name: Setup Python, Poetry, and Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: "3.12"
          poetry-version: "1.8.2"
          install-args: "-E dev -E postgres -E milvus -E external-tools -E tests"

      - name: Run misc unit tests
        env:
          LETTA_PG_PORT: 8888
          LETTA_PG_USER: letta
          LETTA_PG_PASSWORD: letta
          LETTA_PG_DB: letta
          LETTA_PG_HOST: localhost
          LETTA_SERVER_PASS: test_server_token
          PYTHONPATH: ${{ github.workspace }}:${{ env.PYTHONPATH }}
        run: |
          poetry run pytest -s -vv -k "not test_single_path_agent_tool_call_graph.py and not test_tool_rule_solver.py and not test_local_client.py and not test_o1_agent.py and not test_cli.py and not test_tools.py and not test_concurrent_connections.py and not test_quickstart and not test_endpoints and not test_storage and not test_server and not test_openai_client and not test_providers and not test_client.py" tests
