import './global.css';
import { QueryClientProviders } from './QueryClientProviders';

export const metadata = {
  title: 'Welcome to letta',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProviders>{children}</QueryClientProviders>
      </body>
    </html>
  );
}
